import { useEffect, useMemo, useRef, useState } from "react";
import { useRulebook } from "@/store/rulebook";

// Structured Comprehensive Rules, generated by tools/gen-rulebook.mjs and served
// as a static asset. Loaded lazily the first time the modal opens, then cached.
interface Rule { n: string; text: string }
interface Subsection { id: string; title: string; rules: Rule[] }
interface Section { id: string; title: string; subsections: Subsection[] }
interface GlossaryTerm { term: string; def: string }
interface Rulebook { effective: string; sections: Section[]; glossary: GlossaryTerm[] }

let cache: Rulebook | null = null;

function highlight(text: string, term: string) {
  if (!term) return text;
  const idx = text.toLowerCase().indexOf(term.toLowerCase());
  if (idx < 0) return text;
  return (
    <>
      {text.slice(0, idx)}
      <mark className="rounded bg-table-accent/40 px-0.5 text-table-ink">{text.slice(idx, idx + term.length)}</mark>
      {text.slice(idx + term.length)}
    </>
  );
}

export function Rulebook() {
  const { open, setOpen } = useRulebook();
  const [book, setBook] = useState<Rulebook | null>(cache);
  const [err, setErr] = useState(false);
  const [q, setQ] = useState("");
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open || cache) return;
    fetch("/rulebook.json")
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((data: Rulebook) => { cache = data; setBook(data); })
      .catch(() => setErr(true));
  }, [open]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false);
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, setOpen]);

  // Flat search index (built once per book).
  const index = useMemo(() => {
    if (!book) return [] as { n: string; title: string; text: string; kind: "rule" | "term" }[];
    const out: { n: string; title: string; text: string; kind: "rule" | "term" }[] = [];
    for (const s of book.sections)
      for (const ss of s.subsections)
        for (const r of ss.rules) out.push({ n: r.n, title: `${s.title} · ${ss.title}`, text: r.text, kind: "rule" });
    for (const g of book.glossary) out.push({ n: g.term, title: "Glossary", text: g.def, kind: "term" });
    return out;
  }, [book]);

  const results = useMemo(() => {
    const term = q.trim().toLowerCase();
    if (!term) return null;
    return index
      .filter((r) => r.n.toLowerCase().includes(term) || r.text.toLowerCase().includes(term))
      .slice(0, 300);
  }, [index, q]);

  function jumpTo(id: string) {
    setQ("");
    requestAnimationFrame(() => {
      contentRef.current?.querySelector(`#rule-${CSS.escape(id)}`)?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  }

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[9998] flex items-center justify-center bg-black/70 p-2 sm:p-6" onMouseDown={() => setOpen(false)}>
      <div
        className="panel flex h-[90vh] w-full max-w-6xl flex-col overflow-hidden shadow-2xl"
        onMouseDown={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center gap-3 border-b border-table-border px-4 py-3">
          <div className="font-display text-lg text-table-accentSoft">📖 Comprehensive Rules</div>
          {book?.effective && <div className="hidden text-xs text-table-muted sm:block">effective {book.effective}</div>}
          <input
            className="input ml-auto w-full max-w-md !py-1.5"
            placeholder="Search rules & glossary… (e.g. deathtouch, 509, trample)"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            autoFocus
          />
          <button className="rounded-md px-2 py-1 text-table-muted hover:bg-table-panel2 hover:text-table-ink" onClick={() => setOpen(false)} title="Close (Esc)">
            ✕
          </button>
        </div>

        {!book && !err && <div className="flex flex-1 items-center justify-center text-table-muted">Loading rules…</div>}
        {err && <div className="flex flex-1 items-center justify-center text-red-300">Couldn’t load the rulebook.</div>}

        {book && (
          <div className="flex min-h-0 flex-1">
            {/* TOC */}
            <nav className="hidden w-64 shrink-0 overflow-y-auto border-r border-table-border p-3 text-sm md:block">
              {book.sections.map((s) => (
                <div key={s.id} className="mb-3">
                  <div className="mb-1 font-semibold text-table-accentSoft">{s.id}. {s.title}</div>
                  {s.subsections.map((ss) => (
                    <button
                      key={ss.id}
                      className="block w-full truncate rounded px-2 py-0.5 text-left text-table-muted hover:bg-table-panel2 hover:text-table-ink"
                      onClick={() => jumpTo(ss.rules[0]?.n ?? ss.id)}
                      title={ss.title}
                    >
                      {ss.id}. {ss.title}
                    </button>
                  ))}
                </div>
              ))}
              <button
                className="block w-full rounded px-2 py-0.5 text-left font-semibold text-table-accentSoft hover:bg-table-panel2"
                onClick={() => contentRef.current?.querySelector("#glossary")?.scrollIntoView({ behavior: "smooth" })}
              >
                Glossary
              </button>
            </nav>

            {/* Content */}
            <div ref={contentRef} className="min-w-0 flex-1 overflow-y-auto px-5 py-4">
              {results ? (
                <div>
                  <div className="mb-3 text-xs text-table-muted">{results.length} match{results.length === 1 ? "" : "es"}{results.length === 300 ? "+ (showing first 300)" : ""}</div>
                  {results.length === 0 && <div className="text-table-muted">No rules match “{q}”.</div>}
                  {results.map((r, i) => (
                    <div key={i} className="mb-3">
                      <div className="mb-0.5 flex items-baseline gap-2">
                        <span className="font-mono text-xs font-bold text-table-accentSoft">{r.n}</span>
                        <span className="text-[11px] uppercase tracking-wide text-table-muted">{r.title}</span>
                      </div>
                      <p className="whitespace-pre-line text-sm leading-relaxed text-table-ink">{highlight(r.text, q.trim())}</p>
                    </div>
                  ))}
                </div>
              ) : (
                <div>
                  {book.sections.map((s) => (
                    <section key={s.id} className="mb-8">
                      <h2 className="mb-2 font-display text-xl text-table-accentSoft">{s.id}. {s.title}</h2>
                      {s.subsections.map((ss) => (
                        <div key={ss.id} className="mb-5">
                          <h3 id={`rule-${ss.id}`} className="mb-1.5 border-b border-table-border pb-0.5 font-semibold text-table-ink">
                            {ss.id}. {ss.title}
                          </h3>
                          {ss.rules.map((r) => (
                            <div key={r.n} id={`rule-${r.n}`} className="mb-1.5 flex gap-2 scroll-mt-2">
                              <span className="mt-0.5 shrink-0 font-mono text-xs font-bold text-table-muted">{r.n}</span>
                              <p className="whitespace-pre-line text-sm leading-relaxed text-table-ink">{r.text}</p>
                            </div>
                          ))}
                        </div>
                      ))}
                    </section>
                  ))}
                  <section id="glossary" className="mb-8 scroll-mt-2">
                    <h2 className="mb-2 font-display text-xl text-table-accentSoft">Glossary</h2>
                    {book.glossary.map((g) => (
                      <div key={g.term} className="mb-2">
                        <div className="font-semibold text-table-ink">{g.term}</div>
                        <p className="whitespace-pre-line text-sm leading-relaxed text-table-muted">{g.def}</p>
                      </div>
                    ))}
                  </section>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// A small always-available trigger so the rulebook is reachable on every page,
// including the game table (which hides the top nav).
export function RulebookFab() {
  const setOpen = useRulebook((s) => s.setOpen);
  return (
    <button
      className="fixed bottom-3 right-3 z-[9990] flex h-10 w-10 items-center justify-center rounded-full border border-table-border bg-table-panel/90 text-lg shadow-lg backdrop-blur hover:bg-table-panel2"
      title="Rulebook"
      onClick={() => setOpen(true)}
    >
      📖
    </button>
  );
}
