// Authored backlog "issues" for the rulings wizard. Each issue is a MECHANIC /
// clause family (not a raw cost variant), with a matcher used to count cards +
// pull examples, and 3 candidate rulings for how the guided engine should handle
// it. `recommended` is my best guess; for the 12 mechanics the owner already
// ruled on (see memory guided-engine-rulings), his answer is candidate 0.
//
// The generator (tools/gen-rulings.mjs) appends long-tail templates after these.

export const ISSUES = [
  { id: "equip", title: "Equip (Equipment)", match: /^equip\b/i,
    blurb: "Equipment artifacts with an equip cost.",
    recommended: 0,
    candidates: [
      "Equipment enters unattached. Pay the equip cost at sorcery speed to attach it to a creature you control; it grants its bonus while attached. It STAYS on the battlefield when that creature dies and can be re-equipped to another creature later. Only leaves if its own text says so. [owner ruling]",
      "Treat it like an aura: attach on entry, and if the equipped creature dies the equipment goes to the graveyard with it.",
      "Auto-attach to a creature when it enters; re-equip only via a manual move, no cost enforced.",
    ] },
  { id: "activate_only_sorcery", title: "“Activate only as a sorcery”", match: /only as a sorcery|any time you could cast a sorcery/i,
    blurb: "Abilities restricted to sorcery timing.",
    recommended: 0,
    candidates: [
      "The ability can only be activated during your own turn, in a main phase, with an empty stack (sorcery timing). Block it at instant/flash timing. [owner ruling]",
      "Allow it any time you have priority (treat like a normal activated ability).",
      "Allow only during your turn, but in any phase, even with objects on the stack.",
    ] },
  { id: "choose_one", title: "“Choose one —” (modal)", match: /choose one\s*[—-](?! or both)/i,
    blurb: "Modal spells/abilities with a bulleted list of modes.",
    recommended: 0,
    candidates: [
      "The caster picks exactly ONE listed mode when casting; only that mode's effect (and its targets) happens. [owner ruling]",
      "All listed modes happen.",
      "A mode is chosen at random.",
    ] },
  { id: "choose_one_or_both", title: "“Choose one or both —”", match: /choose one or both/i,
    blurb: "Modal spells letting you pick one or both modes.",
    recommended: 0,
    candidates: [
      "The caster chooses one or both listed modes; each chosen mode happens, with targets picked per chosen mode.",
      "Choose exactly one mode.",
      "Both modes always happen.",
    ] },
  { id: "add_any_color", title: "“Add one mana of any color”", match: /add one mana of any color/i,
    blurb: "Mana sources that make any one color.",
    recommended: 0,
    candidates: [
      "Tap for one mana; the player chooses which single color (W/U/B/R/G) to produce. [owner ruling]",
      "Adds one colorless mana.",
      "Adds one mana of every color.",
    ] },
  { id: "add_or", title: "“Add {X} or {Y}” (choose color)", match: /add \{[wubrg]\}(?: or \{[wubrg]\})+/i,
    blurb: "Mana sources listing a choice of colors.",
    recommended: 0,
    candidates: [
      "Tap and choose which ONE of the listed mana types to add. [owner ruling]",
      "Add all listed mana types at once.",
      "Add one colorless mana instead.",
    ] },
  { id: "add_mana_basic", title: "Basic mana ability “{T}: Add {C}/{G}/…”", match: /^\{t\}: add \{[wubrgc0-9/]+\}/i,
    blurb: "Tap for exactly the printed mana.",
    recommended: 0,
    candidates: [
      "Tap to add exactly the printed mana to your pool. An empty diamond {C} = one colorless mana. [owner ruling]",
      "Adds one mana of any color.",
      "Adds generic mana equal to the card's mana value.",
    ] },
  { id: "cycling", title: "Cycling", match: /^cycling /i,
    blurb: "Discard-to-draw ability with a cost.",
    recommended: 0,
    candidates: [
      "Cycling is an activated ability usable any time you could cast an instant: pay the cycling cost and discard this card from your hand, then draw a card. [owner ruling]",
      "Discard it from hand to draw a card, with no cost.",
      "Only on your own turn: pay the cost, discard it, and draw a card.",
    ] },
  { id: "crew", title: "Crew (Vehicles)", match: /^crew \d/i,
    blurb: "Turning a Vehicle into a creature by tapping crew.",
    recommended: 0,
    candidates: [
      "Crew N: tap any number of untapped creatures you control with total power ≥ N; the Vehicle becomes an artifact creature until end of turn. Usable any time you have priority. [owner ruling — please confirm]",
      "Tap exactly one creature with power ≥ N to crew the Vehicle.",
      "The Vehicle is always a creature; ignore crew entirely.",
    ] },
  { id: "pump_for_cost", title: "Firebreathing (activated pump)", match: /:\s*(this creature|it|~) gets [+-]\d+\/[+-]\d+ until end of turn/i,
    blurb: "“{cost}: this gets +X/+Y until end of turn.”",
    recommended: 0,
    candidates: [
      "Pay the listed cost to give the creature +X/+Y until end of turn; repeatable as long as you can pay. [owner ruling]",
      "One-time +X/+Y that lasts the rest of the game.",
      "+X/+Y that lasts only for the current combat.",
    ] },
  { id: "put_rest_bottom", title: "“Put the rest on the bottom … in a random order”", match: /on the bottom of your library in a random order/i,
    blurb: "Leftover cards after a look/draw-and-keep.",
    recommended: 0,
    candidates: [
      "Shuffle the cards you looked at but didn't keep and put them on the BOTTOM of your library. [owner ruling]",
      "Put the leftover cards on top of your library.",
      "Discard the leftover cards.",
    ] },
  { id: "choose_new_targets_copy", title: "Copy spell — “choose new targets”", match: /choose new targets for the copy/i,
    blurb: "Effects that copy a spell.",
    recommended: 0,
    candidates: [
      "The effect creates a copy of the spell on the stack; you may choose new legal targets for the copy, otherwise it keeps the same targets. [owner ruling]",
      "The copy always keeps the original spell's targets.",
      "You re-cast the original spell from your hand.",
    ] },
  { id: "recast_new_target", title: "Re-cast with a new target", match: /cast (this|it) again|copy (this spell|it)(,| and) you may choose/i,
    blurb: "Spells (e.g. Fireball-like) that let you cast again at a new target.",
    recommended: 0,
    candidates: [
      "If the card says you may, re-cast the spell choosing a new target when it resolves/triggers. [owner ruling]",
      "It automatically hits all legal targets.",
      "No repeat; single target only.",
    ] },
  { id: "once_each_turn", title: "“Only once each turn”", match: /only once each turn|triggers only once each turn/i,
    blurb: "Per-turn use limits.",
    recommended: 0,
    candidates: [
      "Track uses per turn; the ability can trigger/activate only once per turn, then is unavailable until your next turn.",
      "No limit — allow it repeatedly.",
      "Once per game.",
    ] },
  { id: "kicker", title: "Kicker", match: /^kicker /i,
    blurb: "Optional additional cost for a bonus.",
    recommended: 0,
    candidates: [
      "Optional additional cost paid as you cast: the player may choose to pay the kicker; if paid, the kicked bonus effect happens.",
      "Always pay the kicker and always get the bonus.",
      "The kicker is free; the spell is always kicked.",
    ] },
  { id: "ward", title: "Ward", match: /^ward[ —{]/i,
    blurb: "Protective tax when targeted by opponents.",
    recommended: 0,
    candidates: [
      "When this permanent becomes the target of a spell or ability an opponent controls, counter that spell/ability unless its controller pays the ward cost.",
      "Opponents simply can't target this permanent (like hexproof).",
      "Opponents pay the ward cost to target it; nothing is countered if they don't.",
    ] },
  { id: "cant_block", title: "“Can't block”", match: /\bcan'?t block\b/i,
    blurb: "Creatures forbidden from blocking.",
    recommended: 0,
    candidates: [
      "Prevent this creature from being declared as a blocker.",
      "It may block but deals no combat damage.",
      "No effect.",
    ] },
  { id: "cant_be_blocked", title: "“Can't be blocked” / evasion", match: /can'?t be blocked\b/i,
    blurb: "Unblockable creatures.",
    recommended: 0,
    candidates: [
      "This creature can't be blocked by any creature; its combat damage goes to the defending player/planeswalker unimpeded.",
      "It can only be blocked by two or more creatures.",
      "No effect.",
    ] },
  { id: "flashback", title: "Flashback", match: /^flashback /i,
    blurb: "Casting from the graveyard, then exiling.",
    recommended: 0,
    candidates: [
      "While this card is in your graveyard you may cast it by paying the flashback cost instead of its mana cost; then exile it as it leaves the stack.",
      "Cast it from the graveyard for its normal mana cost, then exile it.",
      "Return it from the graveyard to your hand for the flashback cost.",
    ] },
  { id: "scry", title: "Scry", match: /\bscry \d/i,
    blurb: "Look at top cards, reorder/bottom them.",
    recommended: 0,
    candidates: [
      "Look at the top N cards of your library; put any number on the bottom and the rest back on top in any order.",
      "Draw N cards.",
      "Put the top N cards on the bottom.",
    ] },
  { id: "surveil", title: "Surveil", match: /\bsurveil \d/i,
    blurb: "Look at top cards, bin or keep on top.",
    recommended: 0,
    candidates: [
      "Look at the top N cards of your library; put any number of them into your graveyard and the rest back on top in any order.",
      "Mill N cards.",
      "Draw N, then discard N.",
    ] },
  { id: "cant_be_countered", title: "“Can't be countered”", match: /can'?t be countered/i,
    blurb: "Spells immune to countermagic.",
    recommended: 0,
    candidates: [
      "Counter effects can't counter this spell; the engine disallows countering it.",
      "Informational only — no enforcement.",
      "It can't be countered only by creatures.",
    ] },
  { id: "gains_haste", title: "Grants haste (until end of turn)", match: /gains? haste/i,
    blurb: "Temporary haste grants.",
    recommended: 0,
    candidates: [
      "Grant haste for the turn: the creature can attack and use {T} abilities despite summoning sickness; clear at cleanup.",
      "Grant haste permanently.",
      "Untap the creature.",
    ] },
  { id: "cant_be_regenerated", title: "“Can't be regenerated”", match: /can'?t be regenerated/i,
    blurb: "Destruction that ignores regen shields.",
    recommended: 0,
    candidates: [
      "Regeneration shields can't save the affected creatures; destruction proceeds and they go to the graveyard.",
      "No effect.",
      "They also can't be blocked.",
    ] },
  { id: "regenerate", title: "Regenerate", match: /regenerate/i,
    blurb: "Regeneration shields.",
    recommended: 0,
    candidates: [
      "Set up a regeneration shield: the next time this creature would be destroyed this turn, instead tap it, remove it from combat, and heal its damage.",
      "Return it from the graveyard to the battlefield.",
      "Prevent all damage to it this turn.",
    ] },
  { id: "discard_that_card", title: "Targeted discard (reveal → discard)", match: /discards that card|reveals? their hand.*you choose/i,
    blurb: "Opponent reveals; a chosen card is discarded.",
    recommended: 0,
    candidates: [
      "After the reveal/choice, the chosen card is put from that player's hand into their graveyard.",
      "The player draws instead of discarding.",
      "The chosen card is exiled.",
    ] },
  { id: "morph", title: "Morph", match: /^morph /i,
    blurb: "Cast face down as a 2/2, flip later.",
    recommended: 0,
    candidates: [
      "You may cast it face down as a 2/2 for {3}; at any time you may pay the morph cost to turn it face up with its real characteristics.",
      "Cast it face up for the morph cost.",
      "It enters face down and can't be turned up.",
    ] },
  { id: "attacks_each_combat", title: "“Attacks each combat if able”", match: /attacks each combat if able/i,
    blurb: "Creatures that must attack.",
    recommended: 0,
    candidates: [
      "This creature must be declared as an attacker each combat if it's able to.",
      "It can't attack.",
      "No effect.",
    ] },
  { id: "cumulative_upkeep", title: "Cumulative upkeep", match: /^cumulative upkeep/i,
    blurb: "Escalating upkeep cost.",
    recommended: 0,
    candidates: [
      "At the beginning of your upkeep put an age counter on it, then pay the cost for EACH age counter or sacrifice it.",
      "Pay the cost once each upkeep or sacrifice it.",
      "No effect.",
    ] },
  { id: "additional_cost_sacrifice", title: "Additional cost: sacrifice", match: /as an additional cost to cast this spell, sacrifice/i,
    blurb: "Spells with a sacrifice cost.",
    recommended: 0,
    candidates: [
      "When casting, the player must sacrifice the required permanent as part of the cost; the spell can't be cast without it.",
      "The sacrifice happens when the spell resolves.",
      "The sacrifice is optional and grants a bonus.",
    ] },
  { id: "etb_choose_one", title: "ETB “choose one” (modal enter)", match: /enters[^.]*, choose one/i,
    blurb: "Modal enters-the-battlefield triggers.",
    recommended: 0,
    candidates: [
      "On entering, its controller chooses one listed mode; that mode happens as a triggered ability.",
      "All modes happen on entry.",
      "The choice is made on your next upkeep.",
    ] },
  { id: "reveal_hand", title: "“Reveals their hand”", match: /reveals? their hand/i,
    blurb: "Forcing a player to reveal their hand.",
    recommended: 0,
    candidates: [
      "The affected player reveals all cards in their hand to everyone (information only); nothing is removed.",
      "The player discards their whole hand.",
      "You take a card from their hand.",
    ] },
  { id: "enchanted_doesnt_untap", title: "“Doesn't untap” (Aura lock)", match: /doesn'?t untap during/i,
    blurb: "Auras that keep a permanent tapped.",
    recommended: 0,
    candidates: [
      "While enchanted, skip this permanent during its controller's untap step (it stays tapped).",
      "The permanent can never become tapped.",
      "No effect.",
    ] },
  { id: "enchant_creature", title: "Enchant creature (Auras)", match: /^enchant /i,
    blurb: "Auras that attach to a creature.",
    recommended: 0,
    candidates: [
      "The Aura attaches to a creature already on the battlefield. The creature's own enter effects happen first, THEN the Aura applies — if the Aura drops its toughness to 0 or otherwise kills it, it dies. The Aura goes to the graveyard when the creature dies, unless its text says otherwise. [owner ruling]",
      "The Aura and creature enter together and the Aura's effect applies before the creature's enter effects.",
      "The Aura floats independently and stays on the battlefield when the creature dies.",
    ] },
  { id: "land_enters_tapped", title: "Land enters tapped", match: /enters? (the battlefield )?tapped/i,
    blurb: "Taplands.",
    recommended: 0,
    candidates: [
      "The land enters tapped and can't be tapped for mana until it untaps on your next turn, unless the card gives more detail. [owner ruling]",
      "It enters untapped.",
      "It enters tapped but may be tapped for mana immediately.",
    ] },
  { id: "mill", title: "Mill", match: /\bmills? \d|puts? the top \d+ cards? of .*library into .*graveyard/i,
    blurb: "Top-of-library to graveyard.",
    recommended: 0,
    candidates: [
      "Put the top N cards of the affected player's library into their graveyard.",
      "That player discards N cards from hand.",
      "Exile the top N cards of the library.",
    ] },
  { id: "proliferate", title: "Proliferate", match: /proliferate/i,
    blurb: "Add another counter to things that have one.",
    recommended: 0,
    candidates: [
      "Choose any number of permanents and/or players that have a counter, and give each another counter of a kind it already has.",
      "Add a +1/+1 counter to each creature you control.",
      "Double all counters in play.",
    ] },

  { id: "manland", title: "Animated / creature-lands (“It's still a land”)", match: /it'?s still a land/i,
    blurb: "Lands that become creatures.", recommended: 0, candidates: [
      "Activating the ability turns the land into a creature with the listed P/T (until end of turn or as stated) while it REMAINS a land; it can still be tapped for mana and, if not summoning-sick, can attack.",
      "It stops being a land while it's a creature.",
      "It becomes a creature permanently.",
    ] },
  { id: "untap_target", title: "Untap a permanent", match: /^untap (that|it|target|this|your)/i,
    blurb: "Effects that untap something.", recommended: 0, candidates: [
      "Untap the referenced permanent (set it from tapped to untapped).",
      "Tap it instead.",
      "It doesn't untap next turn.",
    ] },
  { id: "shuffle_after_search", title: "Shuffle (after search)", match: /^(then )?shuffle|if you search your library this way, shuffle|then that player shuffles/i,
    blurb: "Shuffling a library, usually after a search.", recommended: 0, candidates: [
      "Shuffle the affected library so its order becomes random.",
      "Only shuffle if a card was found.",
      "No shuffle needed.",
    ] },
  { id: "max_speed", title: "Speed / “Start your engines!” / Max speed", match: /start your engines|max speed/i,
    blurb: "The Aetherdrift speed mechanic.", recommended: 0, candidates: [
      "‘Start your engines!’ sets your speed to 1 if you had none. Your speed goes up (max 4) the first time each turn an opponent loses life or one of your creatures attacks; ‘max speed’ abilities are active while your speed is 4. Track a per-player speed value.",
      "‘Start your engines!’ has no mechanical effect.",
      "You always have max speed.",
    ] },
  { id: "impulse_play", title: "Exile-and-play (impulse draw)", match: /you may play (that|those|it|them).* this turn|play (it|them) until end of turn/i,
    blurb: "Exile cards you may play this turn.", recommended: 0, candidates: [
      "Exile the card(s); you may play or cast them this turn (until end of turn). Any still exiled at end of turn stay exiled.",
      "Put the cards into your hand.",
      "You may play them for free forever.",
    ] },
  { id: "top_library_visible", title: "Look at the top of your library", match: /look at the top card of your library any time/i,
    blurb: "Play from / see the top card.", recommended: 0, candidates: [
      "You may look at the top card of your library at any time (revealed to you only); other abilities may let you play it from there.",
      "Reveal the top card to all players.",
      "Draw the top card.",
    ] },
  { id: "enters_with_counters", title: "Enters with +1/+1 counters", match: /enters with .*\+1\/\+1 counters?/i,
    blurb: "ETB with counters (often X).", recommended: 0, candidates: [
      "As it enters the battlefield, put the stated number of +1/+1 counters on it (X = the value paid or the stated condition).",
      "Add the counters on your next upkeep.",
      "It enters with no counters.",
    ] },
  { id: "living_weapon", title: "Living weapon / auto-attach Equipment", match: /when this equipment enters, attach it to|living weapon/i,
    blurb: "Equipment that attaches itself on entry.", recommended: 0, candidates: [
      "When the Equipment enters, attach it to the stated creature (or, for Living weapon, create a 0/0 black Phyrexian Germ token and attach it). It stays on the battlefield if the creature dies.",
      "It attaches to a random creature.",
      "It does nothing until manually equipped.",
    ] },
  { id: "timing_your_turn", title: "“Activate only during your turn”", match: /activate (this ability )?only during your turn/i,
    blurb: "Own-turn timing restriction.", recommended: 0, candidates: [
      "The ability can only be activated during your own turn (any step where you have priority).",
      "Any time you have priority.",
      "Only during your main phase with an empty stack.",
    ] },
  { id: "timing_upkeep", title: "“Activate only during your upkeep”", match: /activate (this ability )?only during your upkeep/i,
    blurb: "Upkeep-only timing.", recommended: 0, candidates: [
      "The ability can only be activated during your upkeep step.",
      "Any time during your turn.",
      "During any player's upkeep.",
    ] },
  { id: "delayed_sacrifice", title: "Delayed sacrifice (end step)", match: /sacrifice it at the beginning of the next end step/i,
    blurb: "Temporary permanents.", recommended: 0, candidates: [
      "Create a delayed trigger: at the beginning of the next end step, sacrifice this permanent.",
      "Sacrifice it immediately.",
      "Sacrifice it at your next upkeep.",
    ] },
  { id: "delayed_exile", title: "Delayed exile (end step)", match: /exile it at the beginning of the next end step/i,
    blurb: "Temporarily controlled/created things.", recommended: 0, candidates: [
      "Delayed trigger: at the beginning of the next end step, exile this permanent.",
      "Exile it immediately.",
      "Exile it at your next upkeep.",
    ] },
  { id: "toxic", title: "Toxic N", match: /^toxic \d/i,
    blurb: "Poison on combat damage.", recommended: 0, candidates: [
      "Toxic N: when this creature deals combat damage to a player, that player also gets N poison counters (10 poison = that player loses).",
      "It deals N extra damage.",
      "No effect.",
    ] },
  { id: "landwalk", title: "Landwalk (Swampwalk, Islandwalk, …)", match: /\b(swamp|island|forest|mountain|plains)walk\b/i,
    blurb: "Conditional unblockable by land type.", recommended: 0, candidates: [
      "This creature can't be blocked as long as the defending player controls a land of the named type.",
      "It can only be blocked by that land type.",
      "No effect.",
    ] },
  { id: "choose_two", title: "“Choose two —”", match: /choose two\s*[—-]/i,
    blurb: "Modal — pick two.", recommended: 0, candidates: [
      "The caster picks exactly two of the listed modes; each chosen mode happens with its own targets.",
      "All modes happen.",
      "Choose one mode.",
    ] },
  { id: "affinity", title: "Affinity", match: /affinity for/i,
    blurb: "Cost reduction per permanent.", recommended: 0, candidates: [
      "Affinity for X: this spell costs {1} less to cast for each X you control (e.g. each artifact).",
      "It costs {1} total if you control any X.",
      "No cost change.",
    ] },
  { id: "day_night", title: "Daybound / Nightbound (day & night)", match: /^(daybound|nightbound)/i,
    blurb: "Transforming day/night creatures.", recommended: 0, candidates: [
      "Track a day/night state for the game. Daybound/nightbound permanents are their front (day) or back (night) face depending on that state, which flips based on how many spells were cast the previous turn.",
      "They simply transform every turn.",
      "Ignore day/night; keep the front face.",
    ] },
  { id: "madness", title: "Madness", match: /^madness /i,
    blurb: "Cast on discard for an alt cost.", recommended: 0, candidates: [
      "When you discard this card, you may exile it instead and then cast it for its madness cost; if you choose not to, put it into your graveyard.",
      "Cast it from your graveyard for the madness cost.",
      "Discarding it lets you draw a card.",
    ] },
  { id: "put_rest_bottom_any", title: "“Put the rest on the bottom … in any order”", match: /on the bottom of your library in any order/i,
    blurb: "Leftover cards, your chosen order.", recommended: 0, candidates: [
      "Put the leftover looked-at cards on the bottom of your library in any order you choose.",
      "Bottom of the library in a random order.",
      "On top of the library instead.",
    ] },
  { id: "reanimate", title: "Reanimation (graveyard → battlefield)", match: /return target creature card from your graveyard to the battlefield|put target creature card from .*graveyard onto the battlefield/i,
    blurb: "Bringing creatures back from the graveyard.", recommended: 0, candidates: [
      "Move the targeted creature card from the graveyard onto the battlefield under your control; it enters as a new object.",
      "Return it to your hand.",
      "Return it to the top of your library.",
    ] },
  { id: "block_only_flying", title: "“Can block only creatures with flying”", match: /can block only creatures with flying/i,
    blurb: "Reach-like block restriction.", recommended: 0, candidates: [
      "This creature can only be declared as a blocker against attackers that have flying.",
      "It can't block at all.",
      "It can block anything.",
    ] },
  { id: "bushido", title: "Bushido N", match: /^bushido \d/i,
    blurb: "Combat pump when blocking/blocked.", recommended: 0, candidates: [
      "Bushido N: whenever this creature blocks or becomes blocked, it gets +N/+N until end of turn.",
      "It always has +N/+N.",
      "No effect.",
    ] },
  { id: "leveler", title: "Level up (Levelers)", match: /:\s*level \d|^level up /i,
    blurb: "Creatures that gain level counters.", recommended: 0, candidates: [
      "Level up {cost}: pay at sorcery speed to put a level counter on it; its P/T and abilities change as it crosses the printed level thresholds.",
      "It gains a level automatically each turn.",
      "No effect.",
    ] },
  { id: "saddle", title: "Saddle N (Mounts)", match: /^saddle \d/i,
    blurb: "Turning on a Mount's bonus.", recommended: 0, candidates: [
      "Saddle N: tap any number of other untapped creatures you control with total power ≥ N to saddle this Mount at sorcery speed; its ‘saddled’ bonus applies this turn.",
      "Tap exactly one creature to saddle it.",
      "The Mount is always saddled.",
    ] },
  { id: "ninjutsu", title: "Ninjutsu", match: /^ninjutsu /i,
    blurb: "Swapping in a Ninja during combat.", recommended: 0, candidates: [
      "Ninjutsu {cost}: during the declare-blockers step, return an unblocked attacker you control to your hand and put this Ninja onto the battlefield tapped and attacking in its place, for the ninjutsu cost.",
      "Cast it for the ninjutsu cost any time.",
      "No effect.",
    ] },
  { id: "choose_background", title: "“Choose a Background”", match: /choose a background/i,
    blurb: "Commander partner variant.", recommended: 0, candidates: [
      "This legendary creature can be paired with a Background enchantment as a second commander when building a Commander deck.",
      "It draws a random Background card.",
      "No effect.",
    ] },
  { id: "if_you_do_discard", title: "“If you do, discard a card”", match: /if you do, discard a card/i,
    blurb: "Linked discard cost/effect.", recommended: 0, candidates: [
      "This is linked to an optional action above it: if you took that action, then discard a card.",
      "Always discard a card.",
      "Draw instead of discarding.",
    ] },

  // ---- keyword mechanics (single authoritative ruling; auto-proposed) ------
  { id: "foretell", title: "Foretell", match: /^foretell /i, blurb: "Exile face down, cast later for the foretell cost.", recommended: 0,
    candidates: ["During your turn you may pay {2} to exile this card from your hand face down. On a later turn you may cast it for its foretell cost."] },
  { id: "buyback", title: "Buyback", match: /^buyback /i, blurb: "Pay extra to return the spell to hand.", recommended: 0,
    candidates: ["Pay the extra buyback cost as you cast this spell; if you do, return it to your hand instead of the graveyard as it resolves."] },
  { id: "echo", title: "Echo", match: /^echo /i, blurb: "Pay again on your next upkeep or sacrifice.", recommended: 0,
    candidates: ["At the beginning of your first upkeep after this entered, sacrifice it unless you pay its echo cost."] },
  { id: "soulshift", title: "Soulshift N", match: /^soulshift \d/i, blurb: "Return a Spirit when this dies.", recommended: 0,
    candidates: ["When this creature dies, you may return target Spirit card with mana value N or less from your graveyard to your hand."] },
  { id: "backup", title: "Backup N", match: /^backup \d/i, blurb: "Enters and buffs a creature.", recommended: 0,
    candidates: ["When this enters, put N +1/+1 counters on a target creature; if it's another creature, it also gains this creature's other keyword abilities until end of turn."] },
  { id: "modular", title: "Modular N", match: /^modular \d/i, blurb: "+1/+1 counters that move on death.", recommended: 0,
    candidates: ["This enters with N +1/+1 counters. When it dies, you may put its +1/+1 counters on a target artifact creature."] },
  { id: "evoke", title: "Evoke", match: /^evoke /i, blurb: "Cast cheap, then sacrifice on entry.", recommended: 0,
    candidates: ["You may cast this for its evoke cost; if you do, sacrifice it when it enters (you still get its enter-the-battlefield trigger)."] },
  { id: "disturb", title: "Disturb", match: /^disturb /i, blurb: "Cast the back face from the graveyard.", recommended: 0,
    candidates: ["You may cast this card transformed (its back face) from your graveyard for its disturb cost. If it would leave the battlefield, exile it instead."] },
  { id: "megamorph", title: "Megamorph", match: /^megamorph /i, blurb: "Morph that flips up with a counter.", recommended: 0,
    candidates: ["Like morph: cast face down as a 2/2 for {3}. Turn it face up any time for its megamorph cost; when you do, put a +1/+1 counter on it."] },
  { id: "bloodthirst", title: "Bloodthirst N", match: /^bloodthirst \d/i, blurb: "Enters bigger if an opponent was damaged.", recommended: 0,
    candidates: ["If an opponent was dealt damage this turn, this creature enters with N +1/+1 counters on it."] },
  { id: "renown", title: "Renown N", match: /^renown \d/i, blurb: "Grows once on combat damage.", recommended: 0,
    candidates: ["When this deals combat damage to a player, if it isn't renowned, put N +1/+1 counters on it and it becomes renowned (happens only once)."] },
  { id: "vanishing", title: "Vanishing N", match: /^vanishing \d/i, blurb: "Time counters then sacrifice.", recommended: 0,
    candidates: ["This enters with N time counters. Remove one at the beginning of your upkeep; when the last is removed, sacrifice it."] },
  { id: "fading", title: "Fading N", match: /^fading \d/i, blurb: "Fade counters then sacrifice.", recommended: 0,
    candidates: ["This enters with N fade counters. At the beginning of your upkeep remove one; if you can't, sacrifice it."] },
  { id: "devour", title: "Devour N", match: /^devour \d/i, blurb: "Eat creatures for counters on entry.", recommended: 0,
    candidates: ["As this enters, you may sacrifice any number of creatures; it enters with N +1/+1 counters for each creature sacrificed this way."] },
  { id: "reconfigure", title: "Reconfigure", match: /^reconfigure /i, blurb: "Equipment creature that attaches.", recommended: 0,
    candidates: ["Pay the reconfigure cost at sorcery speed to attach or unattach this from a creature you control. While attached it's an Equipment (not a creature)."] },
  { id: "entwine", title: "Entwine", match: /^entwine /i, blurb: "Pay to choose all modes.", recommended: 0,
    candidates: ["This is a modal spell: pay the entwine cost in addition to its mana cost to choose ALL of its modes instead of the stated number."] },
  { id: "offspring", title: "Offspring", match: /^offspring /i, blurb: "Pay extra for a 1/1 copy.", recommended: 0,
    candidates: ["You may pay the extra offspring cost as you cast this creature; if you do, when it enters also create a 1/1 token copy of it."] },
  { id: "dash", title: "Dash", match: /^dash /i, blurb: "Haste now, back to hand later.", recommended: 0,
    candidates: ["You may cast this for its dash cost; it enters with haste and you return it to your hand at the beginning of the next end step."] },
  { id: "fabricate", title: "Fabricate N", match: /^fabricate \d/i, blurb: "Counters or Servo tokens on entry.", recommended: 0,
    candidates: ["When this enters, either put N +1/+1 counters on it, or create N 1/1 colorless Servo artifact creature tokens."] },
  { id: "casualty", title: "Casualty N", match: /^casualty \d/i, blurb: "Sacrifice to copy the spell.", recommended: 0,
    candidates: ["As you cast this spell, you may sacrifice a creature with power N or greater; if you do, copy the spell (choosing new targets for the copy if you wish)."] },
  { id: "encore", title: "Encore", match: /^encore /i, blurb: "Graveyard token copies attacking each opponent.", recommended: 0,
    candidates: ["Exile this from your graveyard and pay its encore cost: for each opponent, create a token copy that attacks that opponent this turn, then sacrifice the tokens at end of turn."] },
  { id: "transmute", title: "Transmute", match: /^transmute /i, blurb: "Discard to tutor same-cost card.", recommended: 0,
    candidates: ["Pay the transmute cost and discard this card (sorcery speed) to search your library for a card with the same mana value, reveal it, put it into your hand, then shuffle."] },
  { id: "blitz", title: "Blitz", match: /^blitz /i, blurb: "Haste + draw-on-death, sacrificed EOT.", recommended: 0,
    candidates: ["You may cast this for its blitz cost; it gains haste and 'when this dies, draw a card', and you sacrifice it at the beginning of the next end step."] },
  { id: "dredge", title: "Dredge N", match: /^dredge \d/i, blurb: "Mill to return from graveyard instead of drawing.", recommended: 0,
    candidates: ["If this card is in your graveyard, instead of drawing a card you may mill N cards; if you do, return this card from your graveyard to your hand."] },
  { id: "hideaway", title: "Hideaway N", match: /^hideaway \d/i, blurb: "Exile a card to play later on a condition.", recommended: 0,
    candidates: ["When this enters, look at the top N cards of your library, exile one face down, and put the rest on the bottom. A later condition lets you play that exiled card for free."] },
  { id: "graft", title: "Graft N", match: /^graft \d/i, blurb: "Move +1/+1 counters to entering creatures.", recommended: 0,
    candidates: ["This enters with N +1/+1 counters. Whenever another creature enters, you may move a +1/+1 counter from this onto it."] },
  { id: "annihilator", title: "Annihilator N", match: /^annihilator \d/i, blurb: "Attacker forces sacrifices.", recommended: 0,
    candidates: ["Whenever this creature attacks, the defending player sacrifices N permanents (before blockers)."] },
  { id: "prototype", title: "Prototype", match: /^prototype /i, blurb: "Cast as a smaller artifact.", recommended: 0,
    candidates: ["You may cast this for its prototype cost as an artifact with the listed color and smaller P/T; otherwise it's cast normally with its printed stats."] },
  { id: "basic_landcycling", title: "Basic landcycling", match: /^basic landcycling /i, blurb: "Cycle for a basic land.", recommended: 0,
    candidates: ["Pay the cost and discard this card from your hand to search your library for a basic land card, reveal it, put it into your hand, then shuffle."] },
  { id: "adapt", title: "Adapt N", match: /\badapt \d/i, blurb: "Counters if it has none.", recommended: 0,
    candidates: ["If this creature has no +1/+1 counters on it, put N +1/+1 counters on it."] },
  { id: "monstrosity", title: "Monstrosity N", match: /monstrosity \d/i, blurb: "One-time counters + becomes monstrous.", recommended: 0,
    candidates: ["If this creature isn't monstrous, put N +1/+1 counters on it and it becomes monstrous (this happens only once)."] },
  { id: "bolster", title: "Bolster N", match: /^bolster \d/i, blurb: "Buff your weakest creature.", recommended: 0,
    candidates: ["Choose the creature you control with the least toughness (you choose among ties) and put N +1/+1 counters on it."] },
  { id: "specialize", title: "Specialize", match: /^specialize /i, blurb: "Color-specific transform (rare).", recommended: 0,
    candidates: ["Pay the specialize cost and discard a card of the chosen color to turn this into its matching color back face. (Uncommon mechanic — fall back to manual if unclear.)"] },
  { id: "mutate", title: "Mutate", match: /^mutate /i, blurb: "Merge onto a non-Human creature.", recommended: 0,
    candidates: ["You may cast this for its mutate cost, merging it with a target non-Human creature you own (over or under). The merged permanent has the top card's P/T and name plus all abilities of the pile. (Complex — fall back to manual stacking if needed.)"] },
  { id: "splice", title: "Splice onto Arcane", match: /^splice /i, blurb: "Add this to an Arcane spell.", recommended: 0,
    candidates: ["As you cast an Arcane spell, you may reveal this card from your hand and pay its splice cost to add this card's text to that spell."] },

  // ---- recurring clause patterns -------------------------------------------
  { id: "look_top_n", title: "“Look at the top N cards of your library”", match: /look at the top \w+ cards? of your library/i, blurb: "Peek/dig effects.", recommended: 0,
    candidates: ["Look at the top N cards of your library (revealed to you only), then follow the card's instructions for which to keep and where the rest go."] },
  { id: "make_token_named", title: "Create a Treasure / Food / Clue / Blood token", match: /create (a|\w+) (treasure|food|clue|blood|gold|map|powerstone|incubator)( token)?/i, blurb: "Predefined artifact tokens.", recommended: 0,
    candidates: ["Create the named artifact token with its standard rules text — Treasure: {T}, Sacrifice: add one mana of any color. Food: {2}, {T}, Sacrifice: gain 3 life. Clue: {2}, Sacrifice: draw a card. Blood: {1}, {T}, discard a card, Sacrifice: draw a card."] },
  { id: "protection_from", title: "Protection from [color/quality]", match: /protection from /i, blurb: "Protection (DEBT).", recommended: 0,
    candidates: ["Protection from X means the permanent can't be Damaged by, Enchanted/Equipped by, Blocked by, or Targeted by anything that is X (the 'DEBT' rule). It does NOT gain deathtouch or become unblockable."] },
  { id: "prevent_combat_damage", title: "Prevent combat damage (Fog)", match: /prevent all (combat )?damage/i, blurb: "Fog-style prevention.", recommended: 0,
    candidates: ["Prevent the specified damage that would be dealt this turn (a prevention shield / Fog)."] },
  { id: "prevent_next_n", title: "Prevent the next N damage", match: /prevent the next \d+ damage/i, blurb: "Prevention shield.", recommended: 0,
    candidates: ["Set up a shield that prevents the next N damage that would be dealt to the chosen target this turn."] },
  { id: "gain_keyword_eot", title: "Gains a keyword until end of turn", match: /(gains?|has) (flying|first strike|double strike|deathtouch|trample|lifelink|indestructible|hexproof|menace|vigilance|haste) until end of turn/i, blurb: "Temporary keyword grant.", recommended: 0,
    candidates: ["Grant the listed keyword ability to the affected creature until end of turn (cleared at cleanup)."] },
  { id: "enters_neg_counters", title: "Enters with -1/-1 counters", match: /enters with \w+ -1\/-1 counters?/i, blurb: "ETB with -1/-1 counters.", recommended: 0,
    candidates: ["As this enters the battlefield, put the stated number of -1/-1 counters on it."] },
  { id: "extra_land", title: "Play an additional land", match: /play an additional land/i, blurb: "Extra land drops.", recommended: 0,
    candidates: ["You may play the stated number of additional lands on each of your turns."] },
  { id: "extra_combat", title: "Additional combat phase", match: /additional combat phase/i, blurb: "Extra combat.", recommended: 0,
    candidates: ["After this combat phase, there is an additional combat phase (followed by an additional main phase)."] },
  { id: "extra_turn", title: "Take an extra turn", match: /take an extra turn/i, blurb: "Extra turns.", recommended: 0,
    candidates: ["You take an extra turn after this one. (Guard against loops in guided mode.)"] },
  { id: "monarch", title: "The monarch", match: /become the monarch|the monarch/i, blurb: "Monarch subsystem.", recommended: 0,
    candidates: ["Track a single 'monarch' among players. The monarch draws a card at the beginning of their end step. Whenever a creature deals combat damage to the monarch, that creature's controller becomes the monarch."] },
  { id: "discard_n_target", title: "Target player discards N cards", match: /(target player|that player|each player|each opponent) discards? (a|one|two|three|\d+) cards?/i, blurb: "Discard effects.", recommended: 0,
    candidates: ["The affected player(s) discard the stated number of cards from their hand (that player chooses which, unless the card says 'at random' or 'you choose')."] },
  { id: "copy_no_pay", title: "Cast/copy without paying its mana cost", match: /(cast (the copy|it|that card|this spell)|copy) .*without paying its mana cost/i, blurb: "Free copies/casts.", recommended: 0,
    candidates: ["Create a copy (or cast the referenced card) without paying its mana cost; you still choose targets/modes as normal."] },
  { id: "choose_new_targets_copies", title: "Choose new targets for the copies", match: /choose new targets for the cop(y|ies)/i, blurb: "Copied-spell retargeting.", recommended: 0,
    candidates: ["For each copy created, you may choose new legal targets; otherwise each copy keeps the original targets."] },
  { id: "choose_same_mode", title: "Choose the same mode more than once", match: /choose the same mode more than once/i, blurb: "Repeatable modes.", recommended: 0,
    candidates: ["When choosing this spell's modes, you're allowed to choose the same listed mode multiple times."] },
  { id: "choose_three", title: "“Choose three —”", match: /choose three/i, blurb: "Modal — pick three.", recommended: 0,
    candidates: ["The caster picks exactly three of the listed modes; each chosen mode happens with its own targets."] },
  { id: "choose_one_or_more", title: "“Choose one or more —”", match: /choose one or more/i, blurb: "Modal — pick any number.", recommended: 0,
    candidates: ["The caster chooses one or more of the listed modes; each chosen mode happens with its own targets."] },
  { id: "reverse_landwalk", title: "“Can't attack unless defending player controls [land]”", match: /can'?t attack unless defending player controls (an?|a) (island|swamp|mountain|forest|plains)/i, blurb: "Conditional attack restriction.", recommended: 0,
    candidates: ["This creature can't be declared as an attacker unless the defending player controls the named land type."] },
  { id: "exile_instead_death", title: "“Exile it instead” (of dying / hitting the graveyard)", match: /would (die|be put into (a|your|its owner's|their)?\s*graveyard).*exile it instead/i, blurb: "Death/graveyard replacement.", recommended: 0,
    candidates: ["Replacement effect: if the referenced object would go to the graveyard (or die), exile it instead."] },
  { id: "reveal_top_play", title: "Play with the top card revealed / play from top", match: /play with the top card of your library revealed|look at the top card of your library any time/i, blurb: "Top-of-library play.", recommended: 0,
    candidates: ["Your library's top card is played with it revealed; you may play lands and cast spells from the top of your library as its other abilities allow."] },
  { id: "return_at_end_step", title: "Return to the battlefield at the next end step", match: /return (it|that card|this card) to the battlefield under its owner'?s control at the beginning of the next end step/i, blurb: "Blink/flicker.", recommended: 0,
    candidates: ["Exile now and return it to the battlefield under its owner's control at the beginning of the next end step (it enters as a new object, re-triggering enter effects)."] },
  { id: "additional_cost_discard", title: "Additional cost: discard a card", match: /as an additional cost to cast this spell, discard/i, blurb: "Discard as a cost.", recommended: 0,
    candidates: ["As you cast this spell you must discard the stated card(s) as part of the cost; you can't cast it without doing so."] },
  { id: "explore", title: "Explore", match: /\bit explores\b|\bexplores\.?$/i, blurb: "Explore keyword action.", recommended: 0,
    candidates: ["Reveal the top card of your library. If it's a land, put it into your hand. Otherwise put a +1/+1 counter on the exploring creature, then you may leave the card on top or put it into your graveyard."] },
  { id: "learn", title: "Learn", match: /^learn\.?$/i, blurb: "Learn keyword action.", recommended: 0,
    candidates: ["You may draw a card and then discard a card. (In sets that support Lesson sideboards you could instead fetch a Lesson; here, use draw-then-discard.)"] },
  { id: "clash", title: "Clash", match: /^clash |clash with an opponent/i, blurb: "Clash keyword action.", recommended: 0,
    candidates: ["You and an opponent each reveal the top card of your library, then each may put that card on the bottom. You 'win the clash' if your revealed card has a higher mana value."] },
  { id: "energy", title: "Energy counters {E}", match: /\{e\}/i, blurb: "Energy is a separate resource.", recommended: 0,
    candidates: ["Energy {E} is a per-player resource: 'you get {E}' adds energy counters to your pool; abilities that cost {E} spend them. Track an energy total per player (needs an on-board counter)."] },
  { id: "no_untap_choice", title: "May choose not to untap", match: /choose not to untap this (creature|artifact|permanent)/i, blurb: "Optional skip-untap.", recommended: 0,
    candidates: ["During your untap step you may choose to leave this permanent tapped (don't untap it) — usually to keep a 'while tapped' effect going."] },
  { id: "force_dont_untap", title: "Doesn't untap next untap step", match: /don'?t untap during (their|its) controller'?s next untap step|those creatures don'?t untap/i, blurb: "Tap-down lock.", recommended: 0,
    candidates: ["The affected permanents stay tapped through their controller's next untap step (they skip untapping once)."] },
];
