// Rulings-wizard API. Stores the owner's decision per backlog issue so the
// guided-engine authoring can implement to it. The issue list itself is a static
// asset (client/public/rulings-issues.json, generated by tools/gen-rulings.mjs).
import { Router } from "express";
import { z } from "zod";
import { requireAuth } from "../auth/sessions.js";
import { query } from "../db/pool.js";

export const rulingsRouter = Router();
rulingsRouter.use(requireAuth);

rulingsRouter.get("/answers", async (_req, res) => {
  const { rows } = await query(
    "SELECT issue_id, chosen, custom_text, best, details FROM rule_rulings",
  );
  res.json({ answers: rows });
});

const schema = z.object({
  issueId: z.string().min(1),
  chosen: z.number().int().nullable().optional(),
  customText: z.string().max(4000).nullable().optional(),
  best: z.boolean().optional(),
  details: z.string().max(4000).nullable().optional(),
});

rulingsRouter.post("/answers", async (req, res) => {
  const p = schema.safeParse(req.body);
  if (!p.success) return res.status(400).json({ error: "Invalid ruling payload" });
  const { issueId, chosen = null, customText = null, best = false, details = null } = p.data;
  await query(
    `INSERT INTO rule_rulings (issue_id, chosen, custom_text, best, details, user_id, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, now())
     ON CONFLICT (issue_id) DO UPDATE SET
       chosen = EXCLUDED.chosen, custom_text = EXCLUDED.custom_text,
       best = EXCLUDED.best, details = EXCLUDED.details,
       user_id = EXCLUDED.user_id, updated_at = now()`,
    [issueId, chosen, customText, best, details, req.user!.id],
  );
  res.json({ ok: true });
});
